version: '3.0'

services:

  ############## Elastic Search ##############
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    networks:
      - my-network-name
    ports:
      - 9200:9200
  
  #################### KIBANA ####################
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: kibana
    hostname: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - my-network-name
    depends_on:
      - elasticsearch
  ##########################  NGINX  ################
  nginx: 
    image: nginx:latest
    container_name: production_nginx
  #  volumes:
    #  - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
      - 443:443
      - 80:80
    networks:
      - my-network-name
  awsapi:
    image: darshanraul/awsapi:latest
    container_name: awsapi
    expose:
      - "8080"
    networks:
      - my-network-name
    depends_on:
      - nginx

networks:
  my-network-name:
  
  
  
  
# version: '2'

# services:
#     reverseproxy:
#         image: reverseproxy
#         ports:
#             - 80:80
       
#         restart: always

#     awsapi:
#         depends_on:
#             - reverseproxy
#         image: darshanraul/awsapi
#         restart: always


  
  
  
  
  
