---


- name: Install pip #### assuming python is already installed \
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3
    - python3-pip

- name: Install all dependencies
  pip:
    requirements: {{project_location}}/requirements.txt