---
- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: test_vpc
    cidr_block: "{{vpc_cidr}}"
    region: "{{region}}"
    tags:
      type: primary
  register: primary_vpc



- name: Create subnet for database servers
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ primary_vpc.vpc.id }}"
    cidr: "10.10.0.0/28"
    region: "{{region}}"
    resource_tags:
      Name: Public_Subnet
  register: database_subnet 