---
### Referred the structure in https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx for base skeleton and then built on it
- name: Running python REST API on ubuntu server
  hosts: localhost
  remote_user: root
  # become: yes
  # become_method: sudo

  roles:
    - gitclone
    - install_dependencies
    - runapp